# Generated by Django 6.0 on 2025-12-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField()),
                ('recipe_description', models.CharField()),
                ('recipe_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
